### ISSUE TITLE
[FEATURE]:  Make branch 2.2 operating

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

- [x] make `check-milvus-proto`, `code_checker`, `publish_dev_package`, `pull_request` work on branch 2.2 #1231
- [x] make mergify work on branch 2.2 #1234 
- [x] change README of branch2.2 #1233 

### Describe the solution you'd like

/assign
