### ISSUE TITLE
enable pylint

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus#294]
- [ ] use pylint in our codes
- [ ] add github actions to check codes
- [ ] mention pylint in `contributing` part of the documentation.

**Comment by BossZou** [comment]
See #344

**Comment by BossZou** [comment]
- [x] use pylint in our codes (#344 )
- [x] add github actions to check codes (#344 )
- [ ] mention pylint in `contributing` part of the documentation.

**Comment by BossZou** [comment]
- [x] use pylint in our codes (#344 )
- [x] add github actions to check codes (#344 )
- [x] mention pylint in `contributing` part of the documentation. (#348)
